import axios from "axios";

// Define the API URL
const API_URL = "http://localhost:8080/proizvodi";

// Define the interface for Proizvod
export interface Proizvod {
    id?: number;
    nazivProizvoda: string;
    proizvodjac: string;
    serijskiBroj?: string; // Generated by backend
    drzavaPorijekla: string; // Enum string
    opis?: string;
}

// Function to get all products
const getAll = () => {
    return axios.get<Proizvod[]>(API_URL);
};

// Function to get a product by ID
const getById = (id: number) => {
    return axios.get<Proizvod>(`${API_URL}/${id}`);
};

// Function to create a new product
const create = (data: Proizvod) => {
    return axios.post<Proizvod>(API_URL, data);
};

// Function to update a product
const update = (id: number, data: Proizvod) => {
    return axios.put<Proizvod>(`${API_URL}/${id}`, data);
};

// Function to delete a product
const remove = (id: number) => {
    return axios.delete(`${API_URL}/${id}`);
};

// Function to search products
const findByNaziv = (naziv: string) => {
    return axios.get<Proizvod[]>(`${API_URL}/pretraga/naziv?naziv=${naziv}`);
};

const findByProizvodjac = (proizvodjac: string) => {
    return axios.get<Proizvod[]>(`${API_URL}/proizvodjac/${proizvodjac}`);
};

const searchByProizvodjac = (proizvodjac: string) => {
    return axios.get<Proizvod[]>(`${API_URL}/pretraga/proizvodjac?proizvodjac=${proizvodjac}`);
};

const findByDrzava = (drzava: string) => {
    return axios.get<Proizvod[]>(`${API_URL}/drzava/${drzava}`);
};

// Function to get all available countries (enums)
const getDrzave = () => {
    return axios.get<string[]>(`${API_URL}/drzave`);
};

const ProizvodService = {
    getAll,
    getById,
    create,
    update,
    remove,
    findByNaziv,
    findByProizvodjac,
    searchByProizvodjac,
    findByDrzava,
    getDrzave,
};

export default ProizvodService;
